### ISSUE TITLE
AdmissionController for ServiceAccount JWT sync to Vault?

### ISSUE THREAD

**Issue by flickerfly** [hashicorp/vault-csi-provider#119]
I'm not sure if I understand all of this yet, so I apologize if there are some errors in assumptions. I'm considering this solution for a large setup with many potentially highly dynamic applications. I'd like to avoid manual setup of the ServiceAccount JWT in Vault. Instead, I'd like to have Kubernetes simply inform vault of a new service account and associate it based on namespace with the secrets it should be pulling. I assume an AdmissionController would be the right solution for this. 

Does anything like this exist or is it something you'd consider including?

**Comment by tomhjp** [comment]
Hi @flickerfly. I'm not sure I completely understand your requirements, but with Kubernetes auth, you can specify `*` for the bound service account names, which allows any service account from that namespace to login using the role: https://www.vaultproject.io/api-docs/auth/kubernetes#bound_service_account_names.

That role is what's specified in the SecretProviderClass, so you could set up a SecretProviderClass for each collection of secrets you'd want a service account to pull, and any dynamically created service account could use any of the SecretProviderClasses in its own namespace. This of course assumes that you have acceptable controls over what can be deployed in each kubernetes namespace, because any service account in that namespace would effectively have the same access to secrets as all the others (within the namespace).
