### ISSUE TITLE
Can vault server and vault CSI provider not be in a same kubernetes cluster?

### ISSUE THREAD

**Issue by jammary** [hashicorp/vault-csi-provider#131]
I configured the vault csi as the page https://learn.hashicorp.com/tutorials/vault/kubernetes-secret-store-driver?in=vault/kubernetes , it successed ,but when I use a external vault server, the CSI didn't work ,because they are not in a same k8s cluster, I was wondering if there   is some different configuration between them? please help me ,thanks

**Comment by tomhjp** [comment]
Hi @jammary, the main thing to bear in mind when Vault is external to the cluster is that Vault still needs to be able to access the Kubernetes API in order to use the `TokenReview` endpoint. With the local k8s environments like `minikube` and `kind`, I don't believe that's the case by default, however, it's generally a setting you'll choose as you set up any public cloud hosted Kubernetes solutions.

Note that as of Kubernetes 1.21, using Vault k8s auth becomes trickier when Vault is outside the k8s cluster, because tokens become short-lived by default. Take a look at the available options in our documentation [here](https://www.vaultproject.io/docs/auth/kubernetes#kubernetes-1-21). If you need further guidance from there, feel free to post a detailed set of setup steps and configs you're attempting to use, including any errors you encounter, over at our [discuss forums](https://discuss.hashicorp.com/c/vault/30) and we can try and help you more there.

**Comment by jammary** [comment]
Dear @tomhjp 
Thanks for your kind reply, I tried to disable two options(Disable JWT Issuer Validation &
 Disable use of local CA and service account JWT ) in vault server, it works now

**Comment by jammary** [comment]
Dear @tomhjp 

Thanks for your kind reply, I tried to disable these two options (JWT Issuer Validation/ 
 use of local CA and service account JWT) in vault server kubernetes auth configuration, it works now

**Comment by jammary** [comment]
Dear @tomhjp  but I got a new problem, when I configured the secret provider class with csi provider, it showd me the error "can't find the secret"
my configurations are as below:

#cat secretproviderclass.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: vault-database01
spec:
  provider: vault
  secretObjects:
    - secretName: monitoring-stack-grafana-ini
      type: Opaque
      data:
        - objectName: csi-username01 # References adminUser below
          key: username # Key within k8s secret for this value
  parameters:
    vaultAddress: "https://vault-xxx.xxx.com"
    roleName: "test"
    vaultNamespace: "cn-one-solution"
    objects: |
      - objectName: "csi-username01"
        secretPath: "secret/data/mysql/webapp"
        secretKey: "username"

#cat test.yaml
kind: Pod
apiVersion: v1
metadata:
  name: webapp01
spec:
  serviceAccountName: vault-auth
  containers:
  - image: jweissig/app:0.0.1
    name: webapp
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: monitoring-stack-grafana-ini
            key: username
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "vault-database01"

 The vault csi provider's version is  v0.3.0 and csi driver's version is v1.0.1
How should I configure the vault csi provider and csi driver? I tried to use "-vault-addr =https://vault-xxx.xxx.com" "-write-secrets=false" to configure the containers args parameters of  vault csi provider as the documents [here](https://www.vaultproject.io/docs/platform/k8s/csi/configurations), but It didn't work , could you please help me ?
