### ISSUE TITLE
Use manifest_staging dir for deployment manifest updates

### ISSUE THREAD

**Issue by aramase** [hashicorp/vault-csi-provider#74]
This [PR](https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/pull/71) adds support for health handler. As part of this the livenessprobe and readinessprobe are added to the deployment manifests. However `0.0.7` image doesn't support the `health` handler yet. 

If users try to install the vault provider by running

```bash
kubectl apply -f https://raw.githubusercontent.com/hashicorp/secrets-store-csi-driver-provider-vault/master/deployment/provider-vault-installer.yaml
```

the vault provider will fail to start with livenessprobe errors.

We use [manifest_staging](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/master/manifest_staging) dir in the Secrets Store CSI Driver repo to host the manifest changes prior to release. The manifests are then promoted to the official deployment dir at the time of release. We should follow a similar approach for the vault provider so the master manifests are always valid.

**Comment by tomhjp** [comment]
Thanks for raising this, and apologies for the breakage. We've just merged a PR to support the Vault secrets store CSI driver provider in our helm chart: https://github.com/hashicorp/vault-helm/pull/461

That's going to be our default recommended installation method going forwards, and of course I'll be documenting it in the readme for this repo soon, so I would prefer to delete the deployment folder in favour of using the helm chart. WDYT?

On the topic of the broken test in the driver repo, can we fix that by pinning to a specific commit instead of master? I'll then be raising another driver PR in the near future to replace that with the helm chart once we've released a tag of both that and this provider with all the currently unreleased features in master.

**Comment by aramase** [comment]
> That's going to be our default recommended installation method going forwards, and of course I'll be documenting it in the readme for this repo soon, so I would prefer to delete the deployment folder in favour of using the helm chart. WDYT?

Having helm charts is a big plus. But I'm wondering if we should also keep the deployment folder for users that don't want to use helm? For the Azure provider, we recommend using helm charts because that install the driver + provider but if they wish to use the yamls, we have steps for that documented as well.

> On the topic of the broken test in the driver repo, can we fix that by pinning to a specific commit instead of master? I'll then be raising another driver PR in the near future to replace that with the helm chart once we've released a tag of both that and this provider with all the currently unreleased features in master.

Sounds good! I'll raise a PR to use a fixed commit for now to unblock the tests. We can use https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/483 to track the future update.

**Comment by aramase** [comment]
cc @tomhjp @ritazh

**Comment by tomhjp** [comment]
> Having helm charts is a big plus. But I'm wondering if we should also keep the deployment folder for users that don't want to use helm? For the Azure provider, we recommend using helm charts because that install the driver + provider but if they wish to use the yamls, we have steps for that documented as well.

Yeah that's a fair point. In that case I'm happy to land #75 pretty much as-is. I'll leave a couple of comments in the PR.
